spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: discovery-server
          uri: http://localhost:8080
          predicates:
            - Path=/eureka/wb
          filters:
            - SetPath=/
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/YourSocietyRealm
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/