spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: discovery-server
          uri: http://localhost:8080
          predicates:
            - Path=/eureka/wb
          filters:
            - SetPath=/
        - id: sharing-service
          uri: lb://sharing-service
          predicates:
            - Path=/api/sharing-service/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/YourSocietyRealm
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/