spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/post-service
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: sharing-service
    api-url: /api/${spring.application.name}
  security:
    oauth2:
      resourceserver:
        keycloak:
          server-url: http://localhost:8181
          realm: YourSocietyRealm
          client-id: api-gateway
          admin:
            username: admin
            password: admin
        jwt:
          issuer-uri: ${spring.security.oauth2.resourceserver.keycloak.server-url}/realms/${spring.security.oauth2.resourceserver.keycloak.realm}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0

message:
  advertisement:
    not-found: Could not find advertisement.
  comment:
    not-found: Could not find comment.
  post:
    not-found: Could not find group.
  post-group:
    not-found: Could not find group.
  reaction:
    not-found: Could not find reaction.
  user:
    not-found: Could not find user.

