spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/post-service
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: sharing-service
    api-url: /api/${spring.application.name}
  security:
    oauth2:
      resourceserver:
        keycloak:
          server-url: http://localhost:8181
          realm: YourSocietyRealm
          client-id: api-gateway
          admin:
            username: admin
            password: admin
        jwt:
          issuer-uri: ${spring.security.oauth2.resourceserver.keycloak.server-url}/realms/${spring.security.oauth2.resourceserver.keycloak.realm}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0

message:
  not-found:
    advertisement: Could not find advertisement.
    comment: Could not find comment.
    post: Could not find group.
    post-group: Could not find group.
    reaction: Could not find reaction.
    user: Could not find user.